---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/school/{school_id}/klass/{klass_id}/students":
    get:
      summary: Вывести список студентов класса
      tags:
      - students
      - klasses
      parameters:
      - name: school_id
        in: path
        required: true
        description: ID школы
        schema:
          type: integer
      - name: klass_id
        in: path
        required: true
        description: ID класса
        schema:
          type: integer
      responses:
        '200':
          description: Список студентов
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/Student"
servers:
- url: http://127.0.0.1:3000
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
security: []
