default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: db

development:
  <<: *default
  database: vk_app_development

test:
  <<: *default
  database: vk_app_test

production:
  <<: *default
  database: vk_app_production
  username: <%= ENV['VK_APP_DATABASE_USERNAME'] %>
  password: <%= ENV['VK_APP_DATABASE_PASSWORD'] %>
